# Use a lightweight web server for static files
FROM node:20-alpine AS builder

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
# Copy built files from builder
COPY --from=builder /usr/src/app/build /usr/share/nginx/html

# Expose default Nginx port
EXPOSE 3010

# Start Nginx in foreground
CMD ["nginx", "-g", "daemon off;"]
